#Diese Datei muss in den Ordner provisioning/datasources von grafana kopiert werden
apiVersion: 1

datasources:
  - name: FourWinsDB
    type: mysql
    url: db:3306
    database: 4WINS
    user: fourwins_read
    jsonData:
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
    secureJsonData:
      password: fourwinsread
